# Generated by Django 5.1.7 on 2025-03-21 16:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographic_data', '0002_region_growth_rate_region_population_1965_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='population_1965',
            new_name='historical_1965',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='population_1977',
            new_name='historical_1977',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='population_1988',
            new_name='historical_1988',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='population_2000',
            new_name='historical_2000',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='population_2013',
            new_name='historical_2013',
        ),
        migrations.RemoveField(
            model_name='region',
            name='growth_rate',
        ),
    ]
