# Generated by Django 5.1.7 on 2025-03-21 16:26

import django.contrib.postgres.fields
from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField
import json

def convert_coordinates_to_array(apps, schema_editor):
    Region = apps.get_model('demographic_data', 'Region')
    db_alias = schema_editor.connection.alias
    
    # Créer une nouvelle colonne temporaire
    schema_editor.execute(
        "ALTER TABLE demographic_data_region ADD COLUMN coordinates_temp jsonb"
    )
    
    # Copier les données existantes
    schema_editor.execute(
        "UPDATE demographic_data_region SET coordinates_temp = coordinates"
    )
    
    # Supprimer l'ancienne colonne
    schema_editor.execute(
        "ALTER TABLE demographic_data_region DROP COLUMN coordinates"
    )
    
    # Renommer la nouvelle colonne
    schema_editor.execute(
        "ALTER TABLE demographic_data_region RENAME COLUMN coordinates_temp TO coordinates"
    )

def reverse_convert(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('demographic_data', '0003_rename_population_1965_region_historical_1965_and_more'),
    ]

    operations = [
        migrations.RunPython(
            convert_coordinates_to_array,
            reverse_code=reverse_convert
        ),
    ]
