# Generated by Django 5.1.7 on 2025-03-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demographic_data', '0004_alter_coordinates_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='average_age',
        ),
        migrations.RemoveField(
            model_name='region',
            name='employment_rate',
        ),
        migrations.RemoveField(
            model_name='region',
            name='historical_1965',
        ),
        migrations.RemoveField(
            model_name='region',
            name='historical_1977',
        ),
        migrations.RemoveField(
            model_name='region',
            name='historical_1988',
        ),
        migrations.RemoveField(
            model_name='region',
            name='historical_2000',
        ),
        migrations.RemoveField(
            model_name='region',
            name='historical_2013',
        ),
        migrations.RemoveField(
            model_name='region',
            name='households',
        ),
        migrations.RemoveField(
            model_name='region',
            name='literacy',
        ),
    ]
