# Generated by Django 5.1.7 on 2025-03-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographic_data', '0006_region_average_age_region_employment_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='average_age',
            new_name='female_percentage',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='employment_rate',
            new_name='growth_rate_1977_1988',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='literacy_rate',
            new_name='growth_rate_1988_2000',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='households',
            new_name='population_2023',
        ),
        migrations.AddField(
            model_name='region',
            name='growth_rate_2000_2013',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='growth_rate_2013_2023',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='male_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='total_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
