# Generated by Django 5.1.7 on 2025-03-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographic_data', '0007_rename_average_age_region_female_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='coordinates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
