# Generated by Django 5.1.7 on 2025-03-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographic_data', '0008_alter_region_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='female_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='male_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
