# Generated by Django 5.1.7 on 2025-03-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographic_data', '0009_alter_region_female_population_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='birth_rate_2013',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='birth_rate_2023',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fertility_rate_1977',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fertility_rate_1981',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fertility_rate_1988',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fertility_rate_2000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fertility_rate_2003',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fertility_rate_2011',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fertility_rate_2013',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fertility_rate_2015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fertility_rate_2019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fertility_rate_2023',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
