# Generated by Django 5.1.7 on 2025-03-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographic_data', '0010_region_birth_rate_2013_region_birth_rate_2023_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='child_mortality_2019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='child_mortality_2023',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='infant_mortality_2013',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='infant_mortality_2019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='infant_mortality_2023',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='life_expectancy_1988',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='life_expectancy_2000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='life_expectancy_2023',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='mortality_rate_2013',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='mortality_rate_2023',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
