# Generated by Django 5.1.7 on 2025-03-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographic_data', '0011_region_child_mortality_2019_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='chronic_diseases_nomadic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='chronic_diseases_rural',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='chronic_diseases_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='chronic_diseases_urban',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='disability_rate_female',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='disability_rate_male',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='disability_rate_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='health_insurance_nomadic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='health_insurance_rural',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='health_insurance_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='health_insurance_urban',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
