from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('demographic_data', '0013_region_illiteracy_rate_female_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='illiteracy_rate_male',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='illiteracy_rate_female',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='illiteracy_rate_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='primary_enrollment_rate_male_2000',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='primary_enrollment_rate_female_2000',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='primary_enrollment_rate_total_2000',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='primary_enrollment_rate_male_2013',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='primary_enrollment_rate_female_2013',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='primary_enrollment_rate_total_2013',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='primary_enrollment_rate_male_2023',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='primary_enrollment_rate_female_2023',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='primary_enrollment_rate_total_2023',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='secondary_enrollment_rate_male_2000',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='secondary_enrollment_rate_female_2000',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='secondary_enrollment_rate_total_2000',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='secondary_enrollment_rate_male_2013',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='secondary_enrollment_rate_female_2013',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='secondary_enrollment_rate_total_2013',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='secondary_enrollment_rate_male_2023',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='secondary_enrollment_rate_female_2023',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='secondary_enrollment_rate_total_2023',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='net_primary_rate_male_2000',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='net_primary_rate_female_2000',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='net_primary_rate_total_2000',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='net_primary_rate_male_2013',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='net_primary_rate_female_2013',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='net_primary_rate_total_2013',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='net_primary_rate_male_2023',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='net_primary_rate_female_2023',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='net_primary_rate_total_2023',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='net_secondary_rate_male_2023',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='net_secondary_rate_female_2023',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='net_secondary_rate_total_2023',
            field=models.FloatField(null=True),
        ),
    ] 