# Generated by Django 5.1.7 on 2025-03-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demographic_data', '0014_add_education_fields'),
        ('demographic_data', '0015_add_activity_employment_rates'),
    ]

    operations = [
    ]
